name: do_am_thanh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_sound: ^9.0.0
  intl: ^0.19.0
  kdgaugeview: ^1.0.5
  keep_screen_on: ^3.0.0
  noise_meter: ^4.0.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: 
    - images/splash.jpg
    - images/drawer.jpg

